import type { NextPage } from 'next';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
    const hello = trpc.example.hello.useQuery({ text: 'from tRPC' });
    const { data: session } = useSession();
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="m-6">{session?.user?.name}</div>
            <button onClick={() => signIn()}>login</button>
        </>
    );
};

export default Home;
